In [ ]:
#this also implements team names and outputs transformation via one hot encoding



In [5]:
import pandas as pd

a=pd.read_csv('SERIE A.csv')



In [9]:
raw_df=a[['HomeTeam','AwayTeam', 'B365H', 'B365D', 'B365A', 'FTR']]

In [10]:
raw_df.head()

HomeTeam  AwayTeam  B365H  B365D  B365A FTR
0  Juventus  Cagliari   1.14   8.00  19.00   H
1    Verona    Napoli   8.00   4.75   1.40   A
2  Atalanta      Roma   3.20   3.30   2.30   A
3   Bologna    Torino   3.10   3.30   2.38   D
4   Crotone     Milan   6.00   4.00   1.57   A

In [24]:
raw_df['FTR'].head()

0    H
1    A
2    A
3    D
4    A
Name: FTR, dtype: object

In [25]:
def betting(dl):
    if dl == 'H': return 1
    elif dl== 'D': return 2
    else: return 3
raw_df['Code'] = raw_df['FTR'].map(betting)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """


In [26]:
new_df=raw_df[['HomeTeam','AwayTeam', 'B365H', 'B365D', 'B365A', 'FTR', 'Code']]

In [36]:
new_df.head()

HomeTeam  AwayTeam  B365H  B365D  B365A FTR  Code
0  Juventus  Cagliari   1.14   8.00  19.00   H     1
1    Verona    Napoli   8.00   4.75   1.40   A     3
2  Atalanta      Roma   3.20   3.30   2.30   A     3
3   Bologna    Torino   3.10   3.30   2.38   D     2
4   Crotone     Milan   6.00   4.00   1.57   A     3

In [48]:
# Random Forest Classification
import pandas
from sklearn import model_selection
from sklearn.ensemble import RandomForestClassifier

X = new_df.iloc[:, 2:5]
Y = new_df.iloc[:,6]
seed = 3
num_trees = 100
max_features = 3
kfold = model_selection.KFold(n_splits=10, random_state=seed)
model = RandomForestClassifier(n_estimators=num_trees, max_features=max_features)
results = model_selection.cross_val_score(model, X, Y, cv=kfold)
print(results.mean())

0.5114285714285713


In [49]:
# Logistic Regression

from sklearn import metrics
from sklearn.linear_model import LogisticRegression

# fit a logistic regression model to the data
model = LogisticRegression()
model.fit(X, Y)
print(model)
# make predictions
expected = Y
predicted = model.predict(X)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)
             precision    recall  f1-score   support

          1       0.64      0.79      0.71       150
          2       0.00      0.00      0.00        78
          3       0.54      0.74      0.62       122

avg / total       0.46      0.59      0.52       350

[[118   0  32]
 [ 34   0  44]
 [ 32   0  90]]


C:\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [52]:
kfold = model_selection.KFold(n_splits=10, random_state=seed)
model = RandomForestClassifier(n_estimators=num_trees, max_features=max_features)
results = model_selection.cross_val_score(model, X, Y, cv=kfold)
print(results.mean())

0.5342857142857143


In [53]:
# Gaussian Naive Bayes

from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

# fit a Naive Bayes model to the data
model = GaussianNB()
model.fit(X, Y)
print(model)
# make predictions
expected = Y
predicted = model.predict(X)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

GaussianNB(priors=None)
             precision    recall  f1-score   support

          1       0.79      0.54      0.64       150
          2       0.29      0.55      0.38        78
          3       0.64      0.52      0.57       122

avg / total       0.62      0.53      0.56       350

[[81 56 13]
 [12 43 23]
 [10 49 63]]


In [54]:
kfold = model_selection.KFold(n_splits=10, random_state=seed)
model = RandomForestClassifier(n_estimators=num_trees, max_features=max_features)
results = model_selection.cross_val_score(model, X, Y, cv=kfold)
print(results.mean())

0.5228571428571428


In [ ]:
score, acc = model.evaluate(x_test, y_test)
print('Test score:', score)
print('Test accuracy:', acc)

In [11]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
[0 0 2 0 1 1 2 0 2 1]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
['cold']


C:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
